Time and tagLink test modifications
APMG/apm-titan pull request #37
Opened 2020-04-29 19:36 UTC by Phanx091

2020-04-29 20:32 UTC, kimthompson requested changes

2020-04-29 20:32 UTC, kimthompson commented on src/atoms/TagLink/tests/TagLink.test.js
> +test("We'll have to overhaul TagLink later anyway", () => {
this test should probably be deleted. It's kind of there as a note, but wasn't followed up on, and is not really testing anything.

2020-04-29 20:32 UTC, kimthompson commented on src/atoms/TagLink/tests/TagLink.test.js
>  });
There's room here to test that the `elementClass` prop works as well.

2020-04-29 20:32 UTC, kimthompson commented on src/atoms/TagLink/tests/TagLink.test.js
> +test('TagLink props value matches as expected', () => {
This is kind of a bad name that's held over from the original test. It's hard to tell what's being tested here from that. In this case, I'd probably say that renaming this to "can set tagName and href via props" would be a lot clearer.

2020-04-29 20:32 UTC, kimthompson commented on src/atoms/TagLink/tests/TagLink.test.js
>  // automatically unmount and cleanup DOM after the test is finished.
You should rename your `tests` folder to `__tests__`, as discussed.

2020-04-30 16:40 UTC, Phanx091 reviewed
update

2020-04-30 16:42 UTC, kimthompson approved these changes

2020-04-30 16:57 UTC, merged